config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :order_details
  resources :order_members
  resources :orders
  resources :friends
  resources :group_members
  resources :groups
  resources :friendships

  devise_for :users , :controllers => {registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'users#home'

  get 'users/home' => 'users#home'
  get 'users/show' => 'users#show'
  get 'users/index' => 'users#index'

  get 'orders/:id/cancel' => 'orders#cancel'
  get 'orders/:id/finish' => 'orders#finish'
  mount Judge::Engine => '/judge'

get 'auth/:provider/callback', to: 'sessions#create'
get 'logout', to: 'sessions#destroy'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
	belongs_to  :sender,
                :class_name => "User",
                :foreign_key  => "sender_id"

 	belongs_to  :recipient,
                :class_name => "User",
                :foreign_key  => "recipient_id" 

    has_many :orders
    belongs_to :user
            
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :friend, :class_name => "User"
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user
	has_many :group_members


	validates_uniqueness_of :name, scope: :user_id

	end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
	belongs_to :group
	belongs_to :user

	validates_uniqueness_of :group_id, scope: :user_id
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to  :sender,
                :class_name => "User",
                :foreign_key  => "sender_id"

 	belongs_to  :recipient,
                :class_name => "User",
                :foreign_key  => "recipient_id" 
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "150x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	belongs_to :user
	belongs_to :friend
	has_many :order_members ,dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
	belongs_to :user
	belongs_to :order
end

app/models/order_member.rb
class OrderMember < ActiveRecord::Base
	belongs_to :order
	belongs_to :user
end

app/models/order_observer.rb
class OrderObserver < ActiveRecord::Observer
  observe :order

  def after_create(order)
  	puts "new order added"
    order.logger.info('New order added!')
    # redirect_to order_path, :flash => { :success => "Message" }
  end

  def after_destroy(order)
    order.logger.warn("order with an id of #{order.id} was destroyed!")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook,:google_oauth2]

  has_many :orders
  has_many :groups
  has_many :notifications

  has_many :friendships
  has_many :friends, :through => :friendships

  has_many      :sent, 
                :class_name => "Notification",
                :foreign_key  => "sent_id"

  has_many      :received, 
                :class_name => "Notification", 
                :foreign_key  => "received_id"

   attr_accessor 'just_signed_up'             

# Setup accessible (or protected) attributes for your model
#attr_accessible :email, :password, :remember_me, :name


#   def self.from_omniauth(auth)
#   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
#     user.email = auth.info.email
#     user.password = Devise.friendly_token[0,20]
#     user.name = auth.info.name   # assuming the user model has a name
#     user.image = auth.info.image # assuming the user model has an image
#     user.oauth_token = auth.credentials.token
#     user.oauth_expires_at = Time.at(auth.credentials.expires_at)
#     user.save!
#   end
# end 

def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.name = auth.info.name
        user.password = Devise.friendly_token[0,20]
      end           
end

# def self.from_omniauth(auth)
#   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
#     user.email = auth.info.email
#     user.password = Devise.friendly_token[0,20]
#     user.name = auth.info.name   # assuming the user model has a name
#     #user.image = auth.info.image # assuming the user model has an image
#   end
# end 

# def self.new_with_session(params, session)
#     super.tap do |user|
#       if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
#         user.email = data["email"] if user.email.blank?
#       end
#     end
#   end             



end

app/controllers/order_members_controller.rb
class OrderMembersController < ApplicationController
  before_action :set_order_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /order_members
  # GET /order_members.json
  def index
    @order_members = OrderMember.all
  end

  # GET /order_members/1
  # GET /order_members/1.json
  def show
  end

  # GET /order_members/new
  def new
    @order_member = OrderMember.new
  end

  # GET /order_members/1/edit
  def edit
  end

  # POST /order_members
  # POST /order_members.json
  def create
    @order_member = OrderMember.new(order_member_params)

    respond_to do |format|
      if @order_member.save
        format.html { redirect_to @order_member, notice: 'Order member was successfully created.' }
        format.json { render :show, status: :created, location: @order_member }
      else
        format.html { render :new }
        format.json { render json: @order_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_members/1
  # PATCH/PUT /order_members/1.json
  def update
    respond_to do |format|
      if @order_member.update(order_member_params)
        format.html { redirect_to @order_member, notice: 'Order member was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_member }
      else
        format.html { render :edit }
        format.json { render json: @order_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_members/1
  # DELETE /order_members/1.json
  def destroy
    @order_member.destroy
    respond_to do |format|
      format.html { redirect_to order_members_url, notice: 'Order member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_member
      @order_member = OrderMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_member_params
      params.require(:order_member).permit(:user_id, :order_id, :joined)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def home 
		#@user = Users.find(params[:id])
    	@orders = Order.where(user_id: current_user.id)
    	@friends = User.where(id: Friend.where(user_id: current_user.id))
    	@friendOrders = Order.where(user_id: Friend.where(user_id: current_user.id))

	end	

	def index 
		@users = User.all
	end

	def show 
		@user = current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/order_members_helper.rb
module OrderMembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/order_members/_form.html.erb
<%= form_for(@order_member) do |f| %>
  <% if @order_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_member.errors.count, "error") %> prohibited this order_member from being saved:</h2>

      <ul>
      <% @order_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :joined %><br>
    <%= f.text_field :joined %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_members/edit.html.erb
<h1>Editing Order Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_member %> |
<%= link_to 'Back', order_members_path %>

app/views/order_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Members</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Order</th>
      <th>Joined</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_members.each do |order_member| %>
      <tr>
        <td><%= order_member.user_id %></td>
        <td><%= order_member.order_id %></td>
        <td><%= order_member.joined %></td>
        <td><%= link_to 'Show', order_member %></td>
        <td><%= link_to 'Edit', edit_order_member_path(order_member) %></td>
        <td><%= link_to 'Destroy', order_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order member', new_order_member_path %>

app/views/order_members/new.html.erb
<h1>New Order Member</h1>

<%= render 'form' %>

<%= link_to 'Back', order_members_path %>

app/views/order_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order_member.user_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_member.order_id %>
</p>

<p>
  <strong>Joined:</strong>
  <%= @order_member.joined %>
</p>

<%= link_to 'Edit', edit_order_member_path(@order_member) %> |
<%= link_to 'Back', order_members_path %>